# Generated by Django 2.2.9 on 2020-02-02 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0003_auto_20200126_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('students_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('curator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('birth_date', models.DateField(default='01/01/1980')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=25, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(default='', max_length=25, unique=True)),
                ('password', models.CharField(default='111111', max_length=25)),
                ('is_enabled', models.BooleanField(default=False)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='praepostor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_of_group', to='students.Student'),
        ),
    ]
