# Generated by Django 2.2.9 on 2020-01-09 17:31

from django.db import migrations


def phone_clear(ss):
    # ''.join(x for x in ss if x.isdigit())
    result = ''
    for dig in ss:
        if dig.isdigit():
            result.join(dig)
    return result


def forward(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    for student in Student.objects.all().only('id', 'telephone').iterator():
        student.telephone = phone_clear(student.telephone)
        student.save(update_fields=['telephone'])


class Migration(migrations.Migration):
    dependencies = [
        ('students', '0004_auto_20200103_0935'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
