# Generated by Django 2.2.9 on 2020-01-09 18:07

from django.db import migrations

from faker import Faker


def forward(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    f = Faker()
    for student in Student.objects.all().only('id', 'telephone').iterator():
        student.telephone = f.random_int(min=10000000, max=99999999)
        student.save(update_fields=['telephone'])


class Migration(migrations.Migration):
    dependencies = [
        ('students', '0005_auto_20200109_1731'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
