# Generated by Django 2.2.9 on 2020-01-19 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20200119_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='praepostor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_of_group', to='students.Student'),
        ),
    ]
